import { StudentUser } from "../types";

export const JOB_PROGRAMS: {
  [key: string]: { title: string; details: string[] }[];
} = {
  c1: [
    {
      title: "Bezpieczeństwo pracy",
      details: [
        "BHP w zakresie obsługi wózków widłowych",
        "Zasady poruszania się po placu manewrowym i w magazynie",
        "Bezpieczne techniki podnoszenia i transportu ładunków",
        "Procedury awaryjne i zasady postępowania w sytuacjach niebezpiecznych",
        "Środki ochrony indywidualnej operatora",
      ],
    },
    {
      title: "Obsługa maszyn",
      details: [
        "Budowa i zasada działania wózka widłowego",
        "Codzienne czynności kontrolne przed rozpoczęciem pracy",
        "Prawidłowa technika jazdy i manewrowania",
        "Obsługa układu hydraulicznego i mechanizmu podnoszenia",
        "Wymiana butli gazowych (dla wózków LPG)",
      ],
    },
    {
      title: "Przepisy UDT",
      details: [
        "Ustawa o dozorze technicznym - zakres i interpretacja",
        "Wymagania techniczne dla wózków jezdniowych",
        "Przeglądy okresowe i dokumentacja eksploatacyjna",
        "Obowiązki operatora i pracodawcy według przepisów UDT",
        "Odpowiedzialność prawna w przypadku wykroczeń",
      ],
    },
    {
      title: "Praktyka na placu manewrowym",
      details: [
        "Jazda slalomem i jazda tyłem",
        "Precyzyjne ustawianie wideł i manipulacja ładunkiem",
        "Układanie palet na różnych wysokościach",
        "Jazda z ładunkiem po pochylni i nierównym terenie",
        "Wykonanie parkingu i bezpieczne pozostawienie wózka",
        "Praktyka trwa minimum 20 godzin pod okiem instruktora",
      ],
    },
    {
      title: "Przygotowanie do egzaminu",
      details: [
        "Omówienie struktury egzaminu państwowego UDT",
        "Test próbny z pytań teoretycznych (identyczny z państwowym)",
        "Symulacja egzaminu praktycznego",
        "Najczęstsze błędy i jak ich unikać",
        "Wskazówki dotyczące dokumentacji egzaminacyjnej",
      ],
    },
  ],
  c2: [
    {
      title: "Bezpieczeństwo pracy",
      details: [
        "BHP przy pracy z ładowarkami teleskopowymi",
        "Bezpieczna praca na wysokościach",
        "Ocena warunków gruntu i stabilności maszyny",
        "Zasady bezpiecznej wymiany osprzętu",
        "Procedury awaryjne i ewakuacja z kabiny",
      ],
    },
    {
      title: "Obsługa maszyn",
      details: [
        "Budowa i elementy ładowarki teleskopowej",
        "System hydrauliczny i sterowanie proporcjonalne",
        "Obsługa wysięgnika teleskopowego i mechanizmów",
        "Montaż i demontaż różnych rodzajów osprzętu (widelce, łyżka, kosz)",
        "Codzienne kontrole i konserwacja podstawowa",
      ],
    },
    {
      title: "Przepisy UDT",
      details: [
        "Przepisy UDT dla wielozadaniowych nośników osprzętu",
        "Wymagania dla operatorów ładowarek teleskopowych",
        "Dokumentacja techniczna i książka maszyny",
        "Przeglądy i badania techniczne",
        "Certyfikacja osprzętu zamiennego",
      ],
    },
    {
      title: "Praktyka na placu manewrowym",
      details: [
        "Jazda z wysięgnikiem w różnych pozycjach",
        "Praca na wysokościach z koszem osobowym",
        "Załadunek i manipulacja materiałami budowlanymi",
        "Precyzyjna praca łyżką przy robotach ziemnych",
        "Transport ładunków na terenie nierównym i pochyłym",
        "Szkolenie trwa 40 godzin, w tym 30 godzin praktyki",
      ],
    },
    {
      title: "Przygotowanie do egzaminu",
      details: [
        "Testy przykładowe zgodne z wymaganiami UDT",
        "Symulacja egzaminu praktycznego z każdym rodzajem osprzętu",
        "Przegląd najważniejszych zagadnień technicznych",
        "Analiza typowych błędów egzaminacyjnych",
        "Wsparcie instruktora do dnia egzaminu",
      ],
    },
  ],
  c3: [
    // ... [Content abbreviated for brevity but should be full]
    // Reusing the same content as in App.tsx for c3
    {
      title: "Bezpieczeństwo pracy",
      details: [
        "Podstawy BHP w energetyce",
        "Bezpieczna praca przy urządzeniach elektrycznych",
        "Pierwsza pomoc przy porażeniu prądem",
        "Zasady pracy w strefach zagrożonych",
        "Środki ochrony indywidualnej w energetyce",
      ],
    },
    {
      title: "Obsługa urządzeń",
      details: [
        "Obsługa tablic rozdzielczych i aparatury sterowniczej",
        "Identyfikacja i lokalizacja usterek",
        "Podstawowe pomiary elektryczne",
        "Zasady konserwacji urządzeń elektrycznych",
        "Protokoły eksploatacji i dokumentacja",
      ],
    },
    {
      title: "Przepisy elektroenergetyczne",
      details: [
        "Przepisy eksploatacji urządzeń elektroenergetycznych",
        "Normy i standardy branżowe SEP",
        "Wymagania dla personelu eksploatacyjnego",
        "Dokumentacja techniczna i eksploatacyjna",
        "Odpowiedzialność prawna i ubezpieczenia",
      ],
    },
    {
      title: "Teoria elektryczności",
      details: [
        "Podstawowe pojęcia i prawa elektryczności",
        "Rodzaje prądów i napięć",
        "Układy jednofazowe i trójfazowe",
        "Ochrona przeciwporażeniowa",
        "Interpretacja schematów elektrycznych",
      ],
    },
    {
      title: "Przygotowanie do egzaminu",
      details: [
        "Omówienie wymagań egzaminu kwalifikacyjnego SEP",
        "Testy próbne z zakresu G1",
        "Analiza najczęstszych pytań egzaminacyjnych",
        "Powtórka kluczowych zagadnień",
        "Wskazówki odnośnie przebiegu egzaminu",
      ],
    },
  ],
  c4: [
    {
      title: "Bezpieczeństwo pracy",
      details: [
        "BHP przy obsłudze suwnic i wciągników",
        "Bezpieczne techniki podnoszenia ciężarów",
        "Sygnalizacja i komunikacja z nawiązywaczem",
        "Zasady podczepiania i odczepiania ładunków",
        "Procedury awaryjne przy uszkodzeniu urządzenia",
      ],
    },
    {
      title: "Obsługa maszyn",
      details: [
        "Budowa i rodzaje suwnic (pomostowe, bramowe, obrotowe)",
        "Obsługa wciągników elektrycznych i ręcznych",
        "Sterowanie z poziomu roboczego i z kabiny",
        "Obsługa mechanizmów jazdy i podnoszenia",
        "Kontrola stanu technicznego przed rozpoczęciem pracy",
      ],
    },
    {
      title: "Przepisy UDT",
      details: [
        "Przepisy dozoru technicznego dla dźwignic",
        "Wymagania dla operatorów suwnic kategorii II",
        "Dokumentacja eksploatacyjna i badania techniczne",
        "Przeglądy okresowe i roczne",
        "Obowiązki operatora zgodnie z przepisami UDT",
      ],
    },
    {
      title: "Praktyka na hali produkcyjnej",
      details: [
        "Jazda suwnicą z ładunkiem i bez ładunku",
        "Precyzyjne ustawienie ładunku w wyznaczonych miejscach",
        "Obsługa różnych rodzajów zawiesi i haków",
        "Współpraca z nawiązywaczem - sygnały i komunikacja",
        "Wykonanie manewrów awaryjnych",
        "Szkolenie praktyczne trwa minimum 16 godzin",
      ],
    },
    {
      title: "Przygotowanie do egzaminu",
      details: [
        "Struktura egzaminu UDT dla operatorów dźwignic",
        "Testy próbne - część teoretyczna",
        "Symulacja części praktycznej egzaminu",
        "Omówienie typowych błędów na egzaminie",
        "Dokumentacja wymagana w dniu egzaminu",
      ],
    },
  ],
};

export const MOCK_USERS: {
  [key: string]: { password: string; user: StudentUser };
} = {
  "admin@test.com": {
    password: "admin123",
    user: {
      id: "u1",
      email: "admin@test.com",
      name: "Administrator",
      phone: "+48 123 456 789",
      role: "ADMIN",
    },
  },
  "manager@test.com": {
    password: "manager123",
    user: {
      id: "u2",
      email: "manager@test.com",
      name: "Manager Platformy",
      phone: "+48 234 567 890",
      role: "MANAGER",
    },
  },
  "student@test.com": {
    password: "student123",
    user: {
      id: "u3",
      email: "student@test.com",
      name: "Jan Kowalski",
      phone: "+48 730 101 000",
      company: "ABC Transport Sp. z o.o.",
      role: "STUDENT",
      certifications: [
        {
          id: "cert1",
          name: "Operator wózków jezdniowych",
          courseId: "c1",
          courseName: "Operator Wózków Jezdniowych UDT",
          issueDate: "2020-03-12",
          expirationDate: "2025-03-12",
          status: "expiring-soon",
          certificateUrl: "/certificates/cert1.pdf",
        },
        {
          id: "cert2",
          name: "Operator suwnic",
          courseId: "c2",
          courseName: "Operator Suwnic i Wciągników UDT",
          issueDate: "2021-06-18",
          expirationDate: "2026-06-18",
          status: "expiring-soon",
          certificateUrl: "/certificates/cert2.pdf",
        },
        {
          id: "cert3",
          name: "Operator koparek i ładowarek",
          courseId: "c3",
          courseName: "Obsługa Maszyn Budowlanych",
          issueDate: "2022-09-05",
          expirationDate: "2027-09-05",
          status: "active",
          certificateUrl: "/certificates/cert3.pdf",
        },
        {
          id: "cert4",
          name: "Uprawnienia SEP do 1kV",
          courseId: "c4",
          courseName: "Uprawnienia Elektryczne SEP",
          issueDate: "2019-11-22",
          expirationDate: "2024-11-22",
          status: "expired",
          certificateUrl: "/certificates/cert4.pdf",
        },
        {
          id: "cert5",
          name: "BHP dla pracowników biurowych",
          courseId: "c5",
          courseName: "Szkolenie BHP Podstawowe",
          issueDate: "2023-01-15",
          expirationDate: "2026-01-15",
          status: "active",
          certificateUrl: "/certificates/cert5.pdf",
        },
      ],
      examHistory: [
        {
          id: "exam1",
          courseId: "c1",
          courseName: "Operator Wózków Jezdniowych UDT",
          examType: "final",
          score: 14,
          maxScore: 15,
          passed: true,
          date: "2020-03-10",
          questionsAnswered: [],
        },
        {
          id: "exam2",
          courseId: "c1",
          courseName: "Operator Wózków Jezdniowych UDT",
          examType: "module",
          moduleId: "m1",
          moduleName: "Podstawy BHP",
          score: 19,
          maxScore: 20,
          passed: true,
          date: "2020-02-28",
          questionsAnswered: [],
        },
        {
          id: "exam3",
          courseId: "c2",
          courseName: "Operator Suwnic i Wciągników UDT",
          examType: "final",
          score: 13,
          maxScore: 15,
          passed: true,
          date: "2021-06-15",
          questionsAnswered: [],
        },
        {
          id: "exam4",
          courseId: "c2",
          courseName: "Operator Suwnic i Wciągników UDT",
          examType: "module",
          moduleId: "m2",
          moduleName: "Przepisy eksploatacji",
          score: 17,
          maxScore: 20,
          passed: true,
          date: "2021-06-10",
          questionsAnswered: [],
        },
        {
          id: "exam5",
          courseId: "c3",
          courseName: "Obsługa Maszyn Budowlanych",
          examType: "final",
          score: 15,
          maxScore: 15,
          passed: true,
          date: "2022-09-01",
          questionsAnswered: [],
        },
        {
          id: "exam6",
          courseId: "c4",
          courseName: "Uprawnienia Elektryczne SEP",
          examType: "final",
          score: 11,
          maxScore: 15,
          passed: false,
          date: "2019-11-18",
          questionsAnswered: [],
        },
        {
          id: "exam7",
          courseId: "c4",
          courseName: "Uprawnienia Elektryczne SEP",
          examType: "final",
          score: 14,
          maxScore: 15,
          passed: true,
          date: "2019-11-20",
          questionsAnswered: [],
        },
        {
          id: "exam8",
          courseId: "c5",
          courseName: "Szkolenie BHP Podstawowe",
          examType: "module",
          moduleId: "m1",
          moduleName: "Przepisy BHP",
          score: 20,
          maxScore: 20,
          passed: true,
          date: "2023-01-12",
          questionsAnswered: [],
        },
      ],
    },
  },
  "guardian@test.com": {
    password: "guardian123",
    user: {
      id: "u4",
      email: "guardian@test.com",
      name: "Opiekun Firmy ABC",
      phone: "+48 345 678 901",
      role: "COMPANY_GUARDIAN",
      company: "ABC Sp. z o.o.",
      employeeLimit: 10,
      employees: [
        {
          id: "emp1",
          email: "mateusz.kowalski@abc.pl",
          name: "Mateusz Kowalski",
          phone: "+48 500 111 222",
          status: "active",
          createdDate: "2025-11-15",
          assignedCourses: ["c1"],
        },
        {
          id: "emp2",
          email: "anna.lewandowska@abc.pl",
          name: "Anna Lewandowska",
          phone: "+48 500 222 333",
          status: "active",
          createdDate: "2025-10-20",
          assignedCourses: ["c2"],
        },
        {
          id: "emp3",
          email: "pawel.zawisza@abc.pl",
          name: "Paweł Zawisza",
          phone: "+48 500 333 444",
          status: "pending",
          inviteToken: "token123",
          createdDate: "2026-01-03",
          assignedCourses: ["c1"],
        },
      ],
    },
  },
};
